services:
  brumh_db:
    # Antes era db
    image: mysql:8.0
    container_name: brumh_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - brumh_db_data:/var/lib/mysql # Volumen nuevo
    command: --default-authentication-plugin=mysql_native_password

  brumh_api:
    # Antes era api
    build: .
    container_name: brumh_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - brumh_db
    environment:
      DB_HOST: brumh_db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      BACKEND_URL: ${BACKEND_URL}
      WEB_URL: ${WEB_URL}

  brumh_pma:
    # Antes era vrum_pma
    image: phpmyadmin/phpmyadmin
    container_name: brumh_pma
    links:
      - brumh_db:db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: brumh_db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
  brumh_db_data: # Antes era db_data
