services:
  db:
    image: mysql:8.0
    container_name: vrum_db
    restart: always
    environment:
      # Toma los valores del .env de la raíz
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  api:
    build: .
    container_name: brumh_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./firebase-adminsdk.json:/app/firebase-adminsdk.json
    environment:
      # Conexión interna a la DB
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      # Mercado Pago (Producción)
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      # Otras variables necesarias
      JWT_SECRET: ${JWT_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      BACKEND_URL: ${BACKEND_URL}
      WEB_URL: ${WEB_URL}
      PREMIUM_PAYMENT_URL: ${PREMIUM_PAYMENT_URL}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vrum_pma
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
